language: php

services:
    - mysql

php:
    - 7.1

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpcs src/ --standard=PSR2 -n
    - mysql -u root -e "DROP DATABASE IF EXISTS simple_mapper_test"
    - mysql -u root -e "CREATE DATABASE simple_mapper_test"
    - mysql -u root simple_mapper_test < tests/Data/structure.sql
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --bootstrap=tests/bootstrapCI.php

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
